### ISSUE TITLE
The Grand Informal Todo

### ISSUE THREAD

**Issue by 4d47** [4d47/wren-mode#1]
## The Grand Informal Todo

- [ ] Add string interpolation font-locking
- [ ] Add tests
- [ ] Add indent-region-function
- [ ] Add fill-paragraph-function
- [ ] Add command to link documentation
- [ ] Add Comint integration
- [ ] Add Flycheck support
- [ ] c-populate-syntax-table adds "-", "&", "|" to punctuation, add those as well ?
